// <auto-generated/>
namespace NCS.PaperGeneration.ApiService.Areas.HelpPage.ModelDescriptions
{
    public class CollectionModelDescription : ModelDescription
    {
        public ModelDescription ElementDescription { get; set; }
    }
}