// <auto-generated/>
using System;

namespace NCS.PaperGeneration.ApiService.Areas.HelpPage.ModelDescriptions
{
    public class ParameterAnnotation
    {
        public Attribute AnnotationAttribute { get; set; }

        public string Documentation { get; set; }
    }
}